project:
  type: website
  output-dir: docs

website:
  title: "Nano Memo"
  page-navigation: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: basic_concepts.qmd
        text: Basic concepts
      - href: sequencing_qc.qmd
        text: QC
      - href: alignment.qmd
        text: Alignment
      - href: taxonomy.qmd
        text: Taxonomy
      - href: workflows.qmd
        text: Workflows

  sidebar:
    search: true
    contents:
      - section: "Start here"
        contents:
          - index.qmd
      - section: "Categories"
        contents:
          - basic_concepts.qmd
          - sequencing_qc.qmd
          - alignment.qmd
          - taxonomy.qmd
          - workflows.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    css: styles.css

execute:
  freeze: auto